Add fix for pc-gadget, revert channel to stable
canonical/edgex-ubuntu-core-testing pull request #4
Opened 2023-06-01 10:56 UTC by MonicaisHer

use non-system reserved variable name

2023-06-01 11:18 UTC, farshidtz commented
Config Provider has just be released on latest/stable.

2023-06-01 13:02 UTC, farshidtz requested changes

2023-06-01 13:02 UTC, farshidtz commented on build-gadget.sh
> +git clone https://github.com/snapcore/pc-gadget.git
Why is the branch removed? It is still useful to make it clear that this is based on the core22 gadget:
```suggestion
git clone https://github.com/snapcore/pc-gadget.git --branch=22
```

2023-06-01 14:28 UTC, MonicaisHer commented on build-gadget.sh
> +git clone https://github.com/snapcore/pc-gadget.git
Because they explicitly check out the same commit, the end result would be the same. 

But I understand your point. I will apply your suggestion, thanks.

2023-06-02 08:08 UTC, farshidtz approved these changes
Looks good. Keeping in mind that 2.59.4 snapd has recently been promoted to latest/stable, so the compatibility issue no longer exists. It is nevertheless a good idea to test based on a commit known to be working.

I updated the PR description to resolve both issues on merge, not just one.

2023-06-02 08:13 UTC, merged